### ISSUE TITLE
Can't cluster RabbitMQ nodes using Consul backend

### ISSUE THREAD

**Issue by scalp42** [aweber/rabbitmq-autocluster#38] opened 2015-12-16 22:32 UTC
I set up 3 RabbitMQ nodes ready to go with a Consul agent on each of them,

Using `consul` backend, I can see the nodes being healthy and registering in Consul:

![](https://i.imgur.com/mpfYCjY.png)

RabbitMQ config:

```erlang
  {autocluster,
  [
    {consul_host, "localhost"},
    {consul_port, 8500},
    {consul_service, "rabbitmq-chat"},
    {cluster_name, "chat"},
    {backend, "consul"}
  ]}
```

Unfortunately, judging by `cluster_status`, they didn't join each other:

```
root@rabbitmq-i-bc37e966 /var/log/rabbitmq # rabbitmqctl cluster_status
Cluster status of node 'rabbit@ip-10-52-42-221' ...
[{nodes,[{disc,['rabbit@ip-10-52-42-221']}]},
 {running_nodes,['rabbit@ip-10-52-42-221']},
 {cluster_name,<<"rabbit@ip-10-52-42-221.us-west-2.compute.internal">>},
 {partitions,[]}]

root@rabbitmq-i-d5c9fa11 /var/log/rabbitmq # rabbitmqctl cluster_status
Cluster status of node 'rabbit@ip-10-52-32-55' ...
[{nodes,[{disc,['rabbit@ip-10-52-32-55']}]},
 {running_nodes,['rabbit@ip-10-52-32-55']},
 {cluster_name,<<"rabbit@ip-10-52-32-55.us-west-2.compute.internal">>},
 {partitions,[]}]
```

Any ideas @gmr ?

Thanks in advance!

**Comment by gmr** [comment] 2015-12-16 23:18
Can you provide the RabbitMQ startup logs, particularly with regard to the autocluster plugin's output?

**Comment by mg03** [comment] 2015-12-24 07:49
Hi 

I am having the same issue as scalp42. Consul shows green for checks, but

rabbitmqctl cluster_status
Cluster status of node 'rabbit@my-rabbit' ...
[{nodes,[{disc,['rabbit@my-rabbit']}]},
 {running_nodes,['rabbit@my-rabbit']},
 {cluster_name,<<"rabbit@my-rabbit">>},
 {partitions,[]}]

Shows cluster not formed.

I am running on AWS.

I turned on logging for autocluster and get an error (bold below). Please help fix issue so that we can potentially use it in production environment.


              RabbitMQ 3.6.0. Copyright (C) 2007-2015 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########
              Starting broker...
=INFO REPORT==== 24-Dec-2015::07:33:19 ===
Starting RabbitMQ 3.6.0 on Erlang 18.1
Copyright (C) 2007-2015 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 24-Dec-2015::07:33:19 ===
node           : rabbit@my-rabbit
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : AFFPxNA9bhneV/PNleWkqA==
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@my-rabbit

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
autocluster: GET http://172.31.10.214:8500/v1/health/service/rabbitmq-test?passing&tag=test

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:33:21 GMT"},
                              {"content-length","1677"},
                              {"content-type","application/json"},
                              {"x-consul-index","420"},
                              {"x-consul-knownleader","true"},
                              {"x-consul-lastcontact","0"}],
                             "[{\"Node\":{\"Node\":\"ip-172-31-10-214.us-west-2.compute.internal\",\"Address\":\"172.31.10.214\",\"CreateIndex\":375,\"ModifyIndex\":420},\"Service\":{\"ID\":\"rabbitmq-test\",\"Service\":\"rabbitmq-test\",\"Tags\":[\"test\"],\"Address\":\"\",\"Port\":5672,\"EnableTagOverride\":false,\"CreateIndex\":376,\"ModifyIndex\":420},\"Checks\":[{\"Node\":\"ip-172-31-10-214.us-west-2.compute.internal\",\"CheckID\":\"serfHealth\",\"Name\":\"Serf Health Status\",\"Status\":\"passing\",\"Notes\":\"\",\"Output\":\"Agent alive and reachable\",\"ServiceID\":\"\",\"ServiceName\":\"\",\"CreateIndex\":375,\"ModifyIndex\":375},{\"Node\":\"ip-172-31-10-214.us-west-2.compute.internal\",\"CheckID\":\"service:rabbitmq-test\",\"Name\":\"Service 'rabbitmq-test' check\",\"Status\":\"passing\",\"Notes\":\"RabbitMQ Auto-Cluster Plugin TTL Check\",\"Output\":\"\",\"ServiceID\":\"rabbitmq-test\",\"ServiceName\":\"rabbitmq-test\",\"CreateIndex\":376,\"ModifyIndex\":420}]},{\"Node\":{\"Node\":\"ip-172-31-10-8.us-west-2.compute.internal\",\"Address\":\"172.31.10.8\",\"CreateIndex\":188,\"ModifyIndex\":398},\"Service\":{\"ID\":\"rabbitmq-test\",\"Service\":\"rabbitmq-test\",\"Tags\":[\"test\"],\"Address\":\"\",\"Port\":5672,\"EnableTagOverride\":false,\"CreateIndex\":279,\"ModifyIndex\":398},\"Checks\":[{\"Node\":\"ip-172-31-10-8.us-west-2.compute.internal\",\"CheckID\":\"serfHealth\",\"Name\":\"Serf Health Status\",\"Status\":\"passing\",\"Notes\":\"\",\"Output\":\"Agent alive and reachable\",\"ServiceID\":\"\",\"ServiceName\":\"\",\"CreateIndex\":188,\"ModifyIndex\":188},{\"Node\":\"ip-172-31-10-8.us-west-2.compute.internal\",\"CheckID\":\"service:rabbitmq-test\",\"Name\":\"Service 'rabbitmq-test' check\",\"Status\":\"passing\",\"Notes\":\"RabbitMQ Auto-Cluster Plugin TTL Check\",\"Output\":\"\",\"ServiceID\":\"rabbitmq-test\",\"ServiceName\":\"rabbitmq-test\",\"CreateIndex\":279,\"ModifyIndex\":398}]}]"}}]

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
autocluster: Registering node with consul

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
autocluster: POST http://172.31.10.214:8500/v1/agent/service/register ["{\"ID\":\"rabbitmq-test\",\"Name\":\"rabbitmq-test\",\"Port\":5672,\"Tags\":[\"test\"],\"Check\":{\"Notes\":\"RabbitMQ Auto-Cluster Plugin TTL Check\",\"TTL\":\"30s\"}}"]

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:33:21 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
autocluster: Registered node

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
autocluster: Node is only node in the cluster

<b>
=ERROR REPORT==== 24-Dec-2015::07:33:21 ===
autocluster: Can not communicate with cluster nodes: ['rabbit@ip-172-31-10-214',
                                                      'rabbit@ip-172-31-10-8']
</b>
=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Memory limit set to 3026MB of 7566MB total.

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Disk free limit set to 50MB

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Limiting to approx 1048476 file handles (943626 sockets)

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Database directory at /var/lib/rabbitmq/mnesia/rabbit@my-rabbit is empty. Initialising from scratch...

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
    application: mnesia
    exited: stopped
    type: temporary

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Management plugin: using rates mode 'basic'

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=WARNING REPORT==== 24-Dec-2015::07:33:21 ===
msg_store_persistent: rebuilding indices from scratch

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Adding vhost 'vhost1'

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Creating user 'user'

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Setting user tags for user 'user' to [administrator]

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Setting permissions for 'user' in 'vhost1' to '.*', '.*', '.*'

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
started TCP Listener on [::]:5672

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
autocluster: Starting Consul Health Check TTL Timer

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Management plugin started. Port: 15672

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Statistics database started.
 completed with 7 plugins.

=INFO REPORT==== 24-Dec-2015::07:33:21 ===
Server startup complete; 7 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * webmachine
 * mochiweb
 * amqp_client
 * autocluster
 * rabbitmq_management_agent

=INFO REPORT==== 24-Dec-2015::07:33:36 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:33:36 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:33:36 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:33:51 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:33:51 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:33:51 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:34:06 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:34:06 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:34:06 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:34:21 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:34:21 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:34:21 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:34:36 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:34:36 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:34:36 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:34:51 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:34:51 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:34:51 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:35:06 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:35:06 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:35:06 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:35:21 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:35:21 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:35:21 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:35:36 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:35:36 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:35:36 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:35:51 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:35:51 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:35:51 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:36:06 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

=INFO REPORT==== 24-Dec-2015::07:36:06 ===
autocluster: Response: [{ok,{{"HTTP/1.1",200,"OK"},
                             [{"date","Thu, 24 Dec 2015 07:36:06 GMT"},
                              {"content-length","0"},
                              {"content-type","text/plain; charset=utf-8"}],
                             []}}]

=INFO REPORT==== 24-Dec-2015::07:36:21 ===
autocluster: GET http://172.31.10.214:8500/v1/agent/check/pass/service%3Arabbitmq-test

**Comment by AVVS** [comment] 2016-01-20 21:32
auto cluster registers service on the ip address of the consul-agent instead supplying ip address of the rabbitmq server, I think the root cause is here. I've discovered this when trying to setup dev cluster via docker-compose and was too lazy to embed consul-agent on the same image as the rabbitmq

**Comment by AVVS** [comment] 2016-01-20 21:40
We can see that requests to register service come from another ip, but since we don't specify service address - it's automatically assigned to agent address

<img width="542" alt="screen shot 2016-01-21 at 12 38 50 am" src="https://cloud.githubusercontent.com/assets/1713617/12463934/788d3a8c-bfd7-11e5-9871-c5d7405af75a.png">
<img width="876" alt="screen shot 2016-01-21 at 12 38 58 am" src="https://cloud.githubusercontent.com/assets/1713617/12463932/788c174c-bfd7-11e5-9dbb-0e95aeffbb97.png">
<img width="821" alt="screen shot 2016-01-21 at 12 39 15 am" src="https://cloud.githubusercontent.com/assets/1713617/12463931/788a0088-bfd7-11e5-8073-0d8f26d7f847.png">
<img width="843" alt="screen shot 2016-01-21 at 12 39 22 am" src="https://cloud.githubusercontent.com/assets/1713617/12463933/788c799e-bfd7-11e5-9af5-1d58f5e5dcb4.png">

**Comment by AVVS** [comment] 2016-01-21 18:22
looking through your logs @mg03 - cluster can't form because you don't use long names and EC2 doesn't resolve them, therefore nodes do not know how to communicate with each other

**Comment by mg03** [comment] 2016-01-21 19:51
@AVVS : EC2 can resolve the short names. Ive tested doing ping from ip-172-31-10-214 to ip-172-31-10-8 . and also nslookup :
nslookup ip-172-31-10-8
Server:		172.31.0.2 
Address:	172.31.0.2#53

Non-authoritative answer:
Name:	ip-172-31-10-8.us-west-2.compute.internal
Address: 172.31.10.8

ping ip-172-31-10-8 
PING ip-172-31-10-8.us-west-2.compute.internal (172.31.10.8) 56(84) bytes of data.
64 bytes from ip-172-31-10-8.us-west-2.compute.internal (172.31.10.8): icmp_seq=1 ttl=64 time=0.145 ms
64 bytes from ip-172-31-10-8.us-west-2.compute.internal (172.31.10.8): icmp_seq=2 ttl=64 time=0.156 ms
64 bytes from ip-172-31-10-8.us-west-2.compute.internal (172.31.10.8): icmp_seq=3 ttl=64 time=0.199 ms
64 bytes from ip-172-31-10-8.us-west-2.compute.internal (172.31.10.8): icmp_seq=4 ttl=64 time=0.165 ms

So communication on EC2 level works , can you tell me what port that is used by the clustering plugin?

**Comment by AVVS** [comment] 2016-01-21 19:55
@mg03 my bad then, seen about these issues earlier on. clustering plugin connects via http to whatever port consul is running on and you specify it via CONSUL_PORT (default is 8500). However, you must make sure that consul agent is running on the same machine as rabbitmq, because otherwise it will write consul agent's address and not rabbitmq.

Another questions - rabbitmq is not running inside docker, is it? If you use alpine-linux as base image - it wouldn't work, because it doesn't resolve DNS shortnames, even though you can do it from your host machine. For that you need to get another base image

**Comment by mg03** [comment] 2016-01-21 20:05
@avvs: yeah i think its the absence of the consul agent which is messing around with it. also after i test the clustering bit ill be using it inside container . im leaning towards using the phusion fat container, do you have any pointers on that?

**Comment by AVVS** [comment] 2016-01-21 20:07
Well, I have a small container based on @gre image, but with some optimizations and way less layers https://hub.docker.com/r/makeomatic/alpine-rabbitmq/, which is based on https://github.com/janeczku/docker-alpine-kubernetes with proper DNS resolution. Can't give any better advice than this

**Comment by mg03** [comment] 2016-01-21 20:23
@avvs: can you please share the Dockerfile for your image. I couldnt find it in dockerhub.

**Comment by AVVS** [comment] 2016-01-21 20:26
https://github.com/makeomatic/alpine-node/blob/master/alpine-rabbitmq/Dockerfile

**Comment by AVVS** [comment] 2016-01-21 20:27
Btw, I'm trying to pinpoint root cause of https://groups.google.com/forum/#!topic/rabbitmq-users/5EkwBt2UdIY on VMs, if you see something similar - would be glad for ideas. @gmr if you have any as well - would be cool to hear.

**Comment by mg03** [comment] 2016-01-21 20:28
@avvs:  thanx for the Dockerfile. 
Ill keep an eye out for the latency issue.

**Comment by gmr** [comment] 2016-05-25 00:23
Consul and RABBITMQ_NODENAME improvements are in 0.5.0 which will drop within the next week.

**Closed by gmr** 2016-05-25 00:23 UTC
