### ISSUE TITLE
Example of clustering by AWS_EC2_TAGS with environment variables

### ISSUE THREAD

**Issue by luddd3** [aweber/rabbitmq-autocluster#117] opened 2016-12-02 11:36 UTC
According to the documentation multiple variables should be comma delimited, but I can't see anywhere how to define a single variable. I would be grateful if someone could show me an example of the format of a tag key and value. I have tried with below and others

```bash
$ export AWS_EC2_TAGS=key=value
```

**Comment by voltechs** [comment] 2017-01-20 03:12
Agreed, I've been scouring the internet for this information. Documentation would be much appreciated. I'm currently getting a this as the logs.

I cannot for the life of me figure out what's going on.

```
=CRASH REPORT==== 20-Jan-2017::03:03:38 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.133.0>
    registered_name: []
    exception exit: {bad_return,
                        {{rabbit,start,[normal,[]]},
                         {'EXIT',
                             {function_clause,
                                 [{autocluster,maybe_register,
                                      [error,aws,autocluster_aws],
                                      [{file,"src/autocluster.erl"},
                                       {line,111}]},
                                  {autocluster,init,0,
                                      [{file,"src/autocluster.erl"},
                                       {line,33}]},
                                  {rabbit_boot_steps,
                                      '-run_step/2-lc$^1/1-1-',1,
                                      [{file,"src/rabbit_boot_steps.erl"},
                                       {line,49}]},
                                  {rabbit_boot_steps,run_step,2,
                                      [{file,"src/rabbit_boot_steps.erl"},
                                       {line,49}]},
                                  {rabbit_boot_steps,
                                      '-run_boot_steps/1-lc$^0/1-0-',1,
                                      [{file,"src/rabbit_boot_steps.erl"},
                                       {line,26}]},
                                  {rabbit_boot_steps,run_boot_steps,1,
                                      [{file,"src/rabbit_boot_steps.erl"},
                                       {line,26}]},
                                  {rabbit,start,2,
                                      [{file,"src/rabbit.erl"},{line,687}]},
                                  {application_master,start_it_old,4,
                                      [{file,"application_master.erl"},
                                       {line,273}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 134)
    ancestors: [<0.132.0>]
    messages: [{'EXIT',<0.134.0>,normal}]
    links: [<0.132.0>,<0.31.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 27
    reductions: 98
  neighbours:
```

**Comment by michaelklishin** [comment] 2017-01-26 14:22
This is a duplicate of #104.

**Comment by luddd3** [comment] 2017-01-26 16:25
@michaelklishin Are you sure that my original question/issue is a duplicate of #104? I don't see in what way the issues are related, except for the error message that @voltechs pasted.

**Comment by michaelklishin** [comment] 2017-01-26 16:31
@luddd3 OK, sorry.

**Comment by luddd3** [comment] 2017-01-26 16:45
@michaelklishin No problem! Thank you for giving it a second look =)

**Comment by Veidit** [comment] 2017-02-23 15:58
I actually got stuck here, would be great to add an example, I will try with
AWS_EC2_TAGS=[Node Cluster Name: prod-rabbitmq]

**Comment by Veidit** [comment] 2017-03-06 15:47
- AWS_EC2_TAGS=[{"key", "value"}]
That seems to be a working example, but we need a new release since 1574346 isn't in a proper release yet.

**Comment by Veidit** [comment] 2017-03-09 14:30
Nope, that was not it... @luddd3 Did you find any solutions?

**Comment by luddd3** [comment] 2017-03-09 15:54
@Veidit I have actually not tried since I filed the issue. I think I'll wait until it is included in an official release.

**Comment by Veidit** [comment] 2017-03-09 16:19
Damn, perhaps @michaelklishin can give us a hint?
It's working great when it add it right away to config file, but when I use the environment variables it fails.
I have compiled the plugins yesterday and everything else works great.

**Comment by dcorbacho** [comment] 2017-03-29 10:43
This issue has been addressed in https://github.com/rabbitmq/rabbitmq-autocluster/tree/stable through https://github.com/rabbitmq/rabbitmq-autocluster/pull/7, and the usage is now documented: https://github.com/aweber/rabbitmq-autocluster/wiki/AWS%20Configuration

```
AWS_EC2_TAGS="{\"region\": \"us-west-2\",\"service\": \"rabbitmq\"}"
```

**Comment by gmr** [comment] 2018-02-14 22:11
This plugin was forked by the RabbitMQ team and is now part of RabbitMQ. More information can be found @ https://github.com/rabbitmq/rabbitmq-autocluster

**Closed by gmr** 2018-02-14 22:11 UTC
